QAZIMAAZARSHAD/Voters-Registration-Portal

Style.css, index.html
fixes #11
* `I had made changes in the HTML , CSS file to make it responsive completely for any device `
* `uses some media queries too!`
* `I (Kartikey Dubey) made this Project Responsive under LGM-SOC'21 `
* `NA`
`If you want to test my website then click below`
[Voter's registration Portal](https://kartikey0205.github.io/Voters-Registration-Portal/)
<br>
<br>
<br>
<br>
<br>
@kartikey0205
@QAZIMAAZARSHAD I had made changes according to you , and set the previous version of desktop and previous alignment as well 
Please check my PR …
=> Made Website Completely Responsive

Home.html
fixes #16 
Now document Type is displayed in the dropdown list.
NA
=> Supported docs dropdown added 

Home.html, help.css, help.html
I added a help section page and add to a main page in a footer section and in help section i create a form in which  peoples are write there query and ask for help and i  add a FAQ section also in help desk and it will be updated if we done some research what are the common queries. So thats my task please review it and give the feedback and thank you for assigned me that issue.
-->
=> Added a help section page

Home.html, home_hindi.html, index.html
fixes #41 
Updated Copyright Year.
Please check it.
Thanks.
=> Updated Copyright Year

Home.html, home_hindi.html, index.html
adjusted zoom and language button
=> adjust zoom and language button

Home.html
fixes #
ISSUE #103
form translate to all lang
NA
=> added all lang translation

Home.html, home_hindi.html, js/video.js
fixes #3
* `I had made changes in the all HTML files  , JS file to make it  captcha functionable `
* `Reload captcha icon is not clickable as it is icon so no event can be perform on that directly`
* `Instead of this I had refresh  button which makes captcha functionable `
* `Captcha would be of 6 length and each and single time new captcha reloads`
* `I (Kartikey Dubey) made the Captcha functionable under LGM-SOC'21 `
* `NA`
`If you want to test my website then click below`
[Voter's registration …
=> Made Captcha Functionable

Home.html
fixes #7 
modified the district dropdown
one of the districts radiobox went outside the container
=> changed distrcits dropdown

Home.html, Style.css, help.css, help.html, home_hindi.html, index.html
fixes #8 
Make a hover effect on tiranga logo with orange color
NA
=> Add hover effect on tiranga image

Home.html
As  I was assigned the issue of adding feature on submit button that when the submit button clicks it should pop up a window saying your form has been successfully submitted. And I have done the same I added the feature by writing a separate js Script for the button feature and inside the input, attribute added an id which will be linking the js file 
NA
- [x ] My code follows the code style of this project.
- [x ] I have added tests to cover my changes.
- [x ] All new and existing tests passed.
- [ x] The title of my pull request is a short description of the requested changes.
=> Feature added on Submit Button click

Home.html, Style.css, home_hindi.html
fixes #141 
I have added the hover effect on the help desk button and has also assigned it properly.I have also changed it for Hindi page also.
This Pr is for lgmsoc.
=> Hover effect on help desk button added

Home.html
This update to Home.html fixes issue #146 
The asterisk after Surname is now removed which makes that detail optional to be provided.
fixes #
=> Update Home.html with reference to issue #146

Style.css
fixes #109 
Aligned the on/off text within button boundaries by changing margin values in css.
N/A
=> video on/off button text aligned properly

Home.html, home_hindi.html
fixes #111 
Corrected Date of Birth format from moth/ day/ year  to  day/ month/ year.
NA
=> Corrected Date of Birth format

Home.html, Style.css
fixes #116 
Added space in b/w overlapping fields in declaration section.
NA
=> Added space in b/w overlapping fields

Home.html
fixes #108 
Corrected spelling: parlimentary -> parliamentary
Adress -> Address already done by someone.
NA
=> Corrected spelling mistake

Home.html, help.html, index.html
=> Title logo

README.md
All the spelling and grammatical mistakes in README.md are rectified with reference to issue #161
Do check it out once and merge the pull request :)
fixes #161 
Spelling and grammatical mistakes in README.md are rectified
NA
README.md should be updated.
=> Update README.md with reference to issue #161

Home.html
=> Update home.html with reference to issue #165

Home.html
#31 
fixes #31 
An captcha is added with audio button on pressing it will play captcha .
N/A
Just click on headphone button to play captcha and refresh button to change captcha .
=> Audio recaptcha added

Home.html, Style.css, help.css, help.html, index.html, login.html, sign-up.html
fixes #28
I have added the light and dark mode feature.
- Light Mode
- Dark Mode
-Light mode
-Dark Mode
=> updated the light dark mode

Style.css
fixes #168 
Deleted the transition delay on hover which was causing the delay
=> Add issue #168 to main

help.html
fixes #159 
Enhanced the help desk section.
=> Help Desk Changes

login.html, sign-up.html
Reverts QAZIMAAZARSHAD/Voters-Registration-Portal#185
=> Revert "Show/hide pwd toogle"

Home.html, Style.css, help.html, index.html, login.html, sign-up.html
=> scrolltotop

index.html
fixes #167 
Made the entire start button clickable
NA
Click anywhere on the start button and it will open up the next page.
@QAZIMAAZARSHAD
=> Made entire start button clickable

Home.html, Style.css, forgetPass.html, help.css, help.html, index.html, login.html, sign-up.html
PR against issue #181 Replace header Image
I have also changed the header of the help page. @QAZIMAAZARSHAD
=> PR against issue #181 Replace header Image

Home.html, forgetPass.html, help.html, index.html, login.html, sign-up.html
=> Favicon added

index.html, js/video.js
fixes #144 
I have removed the toggle button and the function because of which it was working.
NA
- [x ] My code follows the code style of this project.
- [x ] All new and existing tests passed.
- [x ] The title of my pull request is a short description of the requested changes.
=> removed video toggle button

Style.css, index.html
Styled the content of the footer.
NA
- [✔️] I have added my name in the contributors list at the end of README.md file.
- [✔️] My code follows the code style of this project.
- [✔️] My change requires a change to the documentation.
- [✔️] I have updated the documentation accordingly.
- [✔️] I have added tests to cover my changes.
- [✔️] All new and existing tests passed.
- [✔️] The title of my pull request is a short description of the requested changes.
=> Footer content nicely placed

Home.html
fixes #210
Resolved empty form submission bug
NA
- [✔️] I have added my name in the contributors list at the end of README.md file.
- [✔️] My code follows the code style of this project.
- [✔️] My change requires a change to the documentation.
- [✔️] I have updated the documentation accordingly.
- [✔️] I have added tests to cover my changes.
- [✔️] All new and existing tests passed.
- [✔️] The title of my pull request is a short description of the requested changes.
=> Resolved details page submission bug

Home.html, Style.css, index.html, login.html, sign-up.html
fixes #4 
Added links in the footer
NA
- [] I have added my name in the contributors list at the end of README.md file.
- [✔️] My code follows the code style of this project.
- [✔️] My change requires a change to the documentation.
- [✔️] I have updated the documentation accordingly.
- [✔️] I have added tests to cover my changes.
- [✔️] All new and existing tests passed.
- [✔️] The title of my pull request is a short description of the requested changes.
=> Footer redesign

Home.html, Style.css, forgetPass.html, help.css, help.html, index.html, login.html, sign-up.html
fixes #219
I changed everything that ask me to correct and change. Made footer responsive as well.
- [✔️] My code follows the code style of this project.
- [✔️] My change requires a change to the documentation.
- [✔️] I have updated the documentation accordingly.
- [✔️] I have added tests to cover my changes.
- [✔️] All new and existing tests passed.
- [✔️] The title of my pull request is a short description of the requested changes.
=> Made footer responsive and other minor changes

Home.html
#23 
fixes #23 
A printer button is added which onclick prints the form.
NA
<br>
After clicking the button
<br/>
Just click on print form button and the printer setting you want and print the form.
=> print form

Home.html, Style.css, forgetPass.html, help.html, login.html, sign-up.html
fixes #219 
I have fixed all the bugs, I guess there're no more issues with the footer. Please check it and tell me if you find any.
=> Fixed all the bugs

Home.html, Style.css
#226 
fixes #226 
Print button modified which will print only form.
`NA`
1.Print button modified
<br>
2.starting of print form
<br>
<br>
3.ending of print form
<br>
<br>
=> Print form functionality added

README.md
fixes #228 
Added new tech stack icon
NA
Add any other context or screenshots about the feature request here
=> Tech stack image updated

Style.css
fixes #226
Please have a look. My PR resolves all of the issues.
=> Improved functionality of print function

help.css, help.html
ISSUE #112 
updated as you instructed
=> changes to faq section

Home.html
#226 
fixes #226 
Functionality of print button added
`NA`
Fill the data and click on print button
&#9745;  My code follows the code style of this project.
&#9745;  I have added tests to cover my changes.
&#9745;  All new and existing tests passed.
&#9745;  The title of my pull request is a short description of the requested changes.
&#9745; Open Source Program names : LGMSOC
=> print functionality added

form-correction.html
=> added correction form

Style.css, sign-up.html
fixes #251 
-->
Added asterisk symbol for required fields.
NA
=> added asterisk symbol

form-correction.html
The submit button was failing because of same id tag like id="name"  repeated in the code multiple number of times and some id tags not linked to the proper input attribute. All these are changed to proper tag names.
NA
We need to write an additional logic to check that dynamically one those fields which are checked in column E are set to required in column F and not all fields, replicating the ideal world scenario.
=> FormCorrection Submit Button Failure Fixed

forgetPass.html, help.html
Help Page form Validation and alert using swal implemented.
NA
=> Help page validation and Alert popup

form-correction.html
1. Gave unique ids and class values to all the input elements & checkboxes in section E & F.
2. Fetched all the fields in the boxes id to get an array of elements of checkbox
3. Since things such as address , name etc consists of multiple input fields, if the checkbox is marked, went to every field to see if it is not empty.
4. Refactored the code to create a seperate function and commented the code for better understanding!
NA
=> Dynamic Validation implemented

Style.css
#262 
fixed
issue number #262 
the theme ball of website for changing the dark and light mode is not in proper position so I fixed its position
=> theme ball setting

form-correction.html
1. Added the state field in section E.
2. Populated the districts on choosing the states using the populate function call when attribute changes.
=> district fetched- FormCorrection Page

Home.html, Style.css, index.js
fixes #6 
**Made a modal pop-up which opens when clicked on "List of supported documents"**
1. In Home.html, i added the "myBtn" named id to "List of supported documents", added ordered list for all main headings 
and unordered list for subpoints.
2. In Style.css, i did styling for modal, modal-content, close , close:hover, close:focus, ::after, ::before, head, ol ,ul
classes, img tag and myBtn id and also changed width of popup from 80% to 65% 
3.Added index.js for proper functioning of modal pop-up.
NA
=> Added a Modal pop-up to display List of Supported Documents

sign-up.html
fixes #257 
Added validation for  sign-up page inputs
NA
=> Validation for Signup page inputs

Home.html, forgetPass.html, form-correction.html, help.html, login.html, sign-up.html
=> Now social media links are opening in another tab.

login.html, sign-up.html
Fixed Email validation filed
TEST CASE-
RES-
2)
RES-
3)
RES-
4)Valid one
RES-
=> fixed #180

Home.html, Style.css, forgetPass.html, form-correction.html, help.css, help.html, login.html, sign-up.html
Check it out: https://suspicious-clarke-a869e9.netlify.app/
=> Issue #241 Fixed all footer issues

sign-up.html
#261 
fixes #261 
&#9745; My code follows the code style of this project.
&#9745; I have updated the documentation accordingly.
&#9745; I have added tests to cover my changes.
&#9745; All new and existing tests passed.
&#9745;The title of my pull request is a short description of the requested changes.
&#9745; Open Source Program names(OPTIONAL: If you participated in any open-source program then please mention the program name here) LGMSOC
=> Captcha added in signup

Home.html, forgetPass.html, form-correction.html, help.html, login.html, sign-up.html
=> footer links addded

Style.css
fixes #297 
- Reduced the width of the banner text animation so that it doesn't go all the way to the width of the display
`NA`
- The text animation after the changes:
https://user-images.githubusercontent.com/74287708/124143193-8a06e280-daa8-11eb-985d-d0a3ac9ab8ec.mp4
=> Silver branch

Home.html, Style.css, forgetPass.html, form-correction.html, help.html, index.html, login.html, sign-up.html
=> changed the logo and prettified the css file

forgetPass.html, login.html, sign-up.html
Issue No. #279 
Changes Made:
1. Css Of Login, Forget Password  & Signup Page Changed.
2. New Font Added.
3. Responsiveness Improved.
=> Improved design Of LoginPage,ForgetPass Page and SignUp Page

forgetPass.html, login.html, sign-up.html
Reverts QAZIMAAZARSHAD/Voters-Registration-Portal#323
=> Revert "Improved design Of LoginPage,ForgetPass Page and SignUp Page"

Style.css, help.css
Reverts QAZIMAAZARSHAD/Voters-Registration-Portal#322
=> Revert "Flip logo"

forgetPass.html, login.html, sign-up.html
Reverts QAZIMAAZARSHAD/Voters-Registration-Portal#324
=> Revert "Revert "Improved design Of LoginPage,ForgetPass Page and SignUp Page""

Home.html, Style.css, help.css, help.html, index.html
=> Issue #328

login.html
Add a Demo/Guest Login #300 
- Added a `Guest Login` button
- Created a `guest()` function that bypasses the username and password requirements with an appropriate message
**Text shown:**
```
'); mywindow.document.close(); // necessary for IE >= 10 myDelay = setInterval(checkReadyState, 10); function checkReadyState() { if (mywindow.document.readyState == "complete") { clearInterval(myDelay); mywindow.focus(); // necessary for IE >= 10 mywindow.print(); mywindow.close(); } } return true; }
```
I'm not sure why this happened, but I'm looking into it.
Current appearance
=> Add guest login option

Style.css
Issue Number - #340 
I have removed the underline from social links inside footer section.
NA
=> Remove underline from social links inside footer

forgetPass.html
Fixed #344
Changed the file "forgetPass.html"
Added the Confirm Password Field to it.
Changed the text of button to reset.
NA
=> Confirm Password Field Added

feedbackform.html, feedbackformsubmitted.html
Issue No. #319
Changes Made: 
1. Feedback "Taken" Replaced With "Received" and Text Changes 
2. Resize:none Property Added
=> Feedback Text Changed and Resize Turned To None!

Style.css
Issue Number - #340 
I have removed the underline from social links inside footer section.
NA
=> Remove underline from social links inside footer 

Home.html, feedbackform.html, feedbackformsubmitted.html, forgetPass.html, form-correction.html, help.html, login.html, sign-up.html
I have added more options of cities in the drop-down list.
NA
Loved to contribute.
We have to add more options in the footer in all HTML files.
=> Drop-Down List Commit

.github/pull_request_template.md
Fixes #357 
Removed a redundant point from pull_request_template.md
DCP21
=> Removing checklist point from pull_request_template.md

submitted.css, submitted.html
Fixes #5
Issue-Fix the image in submitted.html also check the responsiveness of page
The changes I've made:
1. Image got fixed.
2. Added few lines of code for responsiveness of the page in submitted.html and submitted.css
3. Edited the line as mentioned in the issue.
Any unusual behaviour in the code:
NA
Additional context :
Done under lgmsoc'21
=> Responsiveness feature checked of submitted file | Image fixed | Line edited 

index.html
Issue No. #361
Changes Made 👍
Beginning Text Font Changed.
=> Beginning Text Font Changed

Style.css, index.html
Issue Number - #298 
i have added a media file for the mobile view that fits the video when the user open the portal in mobile .
NA
=> In mobile view the opening video does not occupies entire screen #298

Home.html, Style.css, feedbackform.html, feedbackformsubmitted.html, forgetPass.html, form-correction.html, help.css, help.html, index.html, login.html, sign-up.html
#303 
I have changed the toggle button position from top to bottom left in all pages.
I have resolve all merge conflicts and added at bottom of all pages.
You can see the button
=> Toggle button

login.html
Changed Position of dark and Light Toggle button
NA
=> Dark Light Toggle Button Shifted In Footer

Home.html, Style.css, feedbackform.html, feedbackformsubmitted.html, forgetPass.html, form-correction.html, help.css, help.html, login.html, sign-up.html
=> flip logo feature fixed

Home.html
Improve the UI/UX of the hom page content not including the header and footer
NA
this is the link (kindly navigate to homepage to view the changes):
https://leesiangwei.github.io/Voters-Registration-Portal/
screenshots of new changes made:
NA
=> Improvement of UI/UX in hompage content v3

form-correction.html
I have added a little more bottom padding to the text as it seemed like a little padding bottom was requires. Also, i changed the text color so that the text should be properly visible.
NA
=> Corrected copyright text in the form-correction.html 

form-correction.html
Now the text completely look similar to other pages text. Sorry for inconvenience, this time it is correct. You can see it below
=> Corrected copyright text successfully 

Style.css, feedbackformsubmitted.html
Aligned text properly and made the page responsive
NA
https://gunjan-g.github.io/Voters-Registration-Portal/feedbackformsubmitted.html
=> Improved Feedback Form submission page

Home.html, feedbackform.html, feedbackformsubmitted.html, forgetPass.html, form-correction.html, help.html, login.html, sign-up.html
Dark Mode / Theme has been now made persistent. If one selects dark theme , then all subsequent visits to the pages will be in dark theme unless the user changes it.
NA
Test link : [https://developer-diganta.github.io/Voters-Registration-Portal/index.html](url)
=> Made Dark Mode / Theme persistent

Home.html, feedbackform.html, feedbackformsubmitted.html, forgetPass.html, form-correction.html, help.html, login.html, sign-up.html
I have added the new address and it changes as the user selects some other city, the address gets changed. I have also added the default as delhi.
NA
https://user-images.githubusercontent.com/72425181/126258366-09d34629-2147-497c-907b-ea90c802bee2.mp4
I have provided a video, please have a look.
=> Address of regional office should display on selecting every state

Home.html, feedbackform.html, feedbackformsubmitted.html, forgetPass.html, form-correction.html, help.html, login.html, sign-up.html
I have added different address for different cities as one address can't be valid for all of the cities.
NA
I will add a video down below.
https://user-images.githubusercontent.com/72425181/126597548-3144b1b5-5c42-4fb4-ab01-3c9978b2b021.mp4
=> Different addresses for different cities

help.css, help.html
You can text the mobile view in this website http://mattkersley.com/responsive/
I add responsive text style in help.html, remove the class of input-row
NA
NA
=> Add Responsive Text in voter registration Help page

Home.html
I have added a little space below the buttons which makes it look more clean.
NA
=> Added bottom padding

Home.html, Style.css, form-correction.html
created a log out button which would redirect the user to login page from home and form correction pages
**NA**
https://user-images.githubusercontent.com/70878223/126832152-b2ac1882-1aef-4c5d-9805-f9c3b1c1e11a.mp4
created this redirect on home.html and formcorrection.html
=> Create a logout button on registration portal

Style.css, help.css, login.html
Shifted the dark/light toggle button in footer in mobile view
NA
https://anushruti11.github.io/Voters-Registration-Portal/index.html
@nlok5923 check this out.
=> Shifting the dark/light toggle button in mobile view 

forgetPass.html, login.html, sign-up.html
improved password verification on login sign-up and forget password pages
**NA**
Add the deployment link here.
https://formvalidate11.netlify.app/
=> password verification done

help.css
Aligned Help page in desktop view
NA
=> Aligned help page in desktop view

form-correction.html
Fixed #421
NA
https://garima-7.github.io/Voters-Registration-Portal/
=> UI Improvement of form-correction.html

Home.html, Style.css, feedbackform.html, feedbackformsubmitted.html, forgetPass.html, form-correction.html, help.css, help.html, login.html, sign-up.html
Add tel link to the telephone.
Add mailto link to the email.
Remove the underline when hovering on the help desk button.
All three buttons (Call, Email, Help Desk) use same style.
NA
=> Add mailto link in footer and correct hover effect on help button

Style.css
Added specific id's for each button in style.css changing the color of Font Setting and Logout  buttons as required.
#screenshot (after fix) attached below-
=> Fixes #429 Change color of buttons in home and form-correction page

Home.html, form-correction.html
=> Fix : Select Language Redundancy

Home.html, Style.css, form-correction.html, help.css, login.html
Fixed the overlapping of toggle button of every page in mobile view
you can check this here:
https://aasthasaxena217.github.io/Voters-Registration-Portal/login.html
=> Removed overlapping bug of dark/light toggle button of every page

README.md
Fixes #441 
Added hacktoberfest 2021 logo in Readme
=> Added hacktoberfest 2021 logo in Readme
